<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LegacyBanking.Domain\LegacyBanking.Domain.csproj"/>
    <Reference Include="System.Runtime.Serialization"/>
    <Reference Include="System.Configuration"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3"/>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.0"/>
  </ItemGroup>
</Project>