<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LegacyBanking.Domain\LegacyBanking.Domain.csproj" />
    <ProjectReference Include="..\LegacyBanking.Data\LegacyBanking.Data.csproj" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>
</Project>
