<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LegacyBanking.Application\LegacyBanking.Application.csproj"/>
    <ProjectReference Include="..\..\src\LegacyBanking.Data\LegacyBanking.Data.csproj"/>
    <ProjectReference Include="..\..\src\LegacyBanking.Domain\LegacyBanking.Domain.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.3"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
  </ItemGroup>
</Project>
